// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FuzzyFileSearchSessionError } from "./FuzzyFileSearchSessionError";

/**
 * An operation failure in a fuzzy file-search session.
 *
 * This notification does not confirm that session cleanup has completed.
 * The session stop response and server shutdown own their cleanup results.
 */
export type FuzzyFileSearchSessionFailedNotification = {
/**
 * Caller-supplied session ID, limited to 256 UTF-8 bytes at admission.
 */
sessionId: string,
/**
 * Query associated with the failure, bounded by the effective search policy.
 */
query: string, error: FuzzyFileSearchSessionError, };
