// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FuzzyFileSearchSessionErrorKind } from "./FuzzyFileSearchSessionErrorKind";

export type FuzzyFileSearchSessionError = { kind: FuzzyFileSearchSessionErrorKind,
/**
 * Diagnostic bounded by the emitting adapter to 2048 UTF-8 bytes.
 */
message: string, };
