// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable wire categories independent of the selected search implementation.
 */
export type FuzzyFileSearchSessionErrorKind = "invalidInput" | "unsupportedVersion" | "unsupportedOption" | "unknownLease" | "closedLease" | "staleEpoch" | "resourceExhausted" | "searchFailed" | "transportLost" | "forcedShutdown";
